---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org1-ca-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem