---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: org1-peer0-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem