---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer0-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem